import type { Component, Meal, Targets } from './types'

// Starter library so the app is useful immediately. Nutrition is per single
// serving; `servingsPerBatch` is how many servings one prepped batch yields
// (the ingredient list is for that one batch).

export const SEED_COMPONENTS: Component[] = [
  // ----- Bases -------------------------------------------------------------
  {
    id: 'base-jasmine-rice',
    name: 'Jasmine Rice',
    category: 'base',
    flavorProfiles: ['East Asian', 'Thai', 'Neutral'],
    nutrition: { calories: 205, protein: 4, carbs: 45, fat: 0 },
    servingsPerBatch: 6,
    ingredients: [{ name: 'Jasmine rice', quantity: 2, unit: 'cup' }],
  },
  {
    id: 'base-cilantro-lime-rice',
    name: 'Cilantro-Lime Rice',
    category: 'base',
    flavorProfiles: ['Mexican'],
    nutrition: { calories: 215, protein: 4, carbs: 46, fat: 2 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Long-grain rice', quantity: 2, unit: 'cup' },
      { name: 'Lime', quantity: 1, unit: 'whole' },
      { name: 'Cilantro', quantity: 1, unit: 'bunch' },
    ],
  },
  {
    id: 'base-farro',
    name: 'Farro',
    category: 'base',
    flavorProfiles: ['Mediterranean', 'Italian', 'Neutral'],
    nutrition: { calories: 200, protein: 7, carbs: 40, fat: 1 },
    servingsPerBatch: 5,
    ingredients: [{ name: 'Farro', quantity: 1.5, unit: 'cup' }],
  },
  {
    id: 'base-quinoa',
    name: 'Quinoa',
    category: 'base',
    flavorProfiles: ['Mediterranean', 'Neutral'],
    nutrition: { calories: 185, protein: 8, carbs: 32, fat: 3 },
    servingsPerBatch: 5,
    ingredients: [{ name: 'Quinoa', quantity: 1.5, unit: 'cup' }],
  },
  {
    id: 'base-greens',
    name: 'Mixed Greens',
    category: 'base',
    flavorProfiles: ['Neutral', 'Mediterranean', 'American'],
    nutrition: { calories: 15, protein: 1, carbs: 3, fat: 0 },
    servingsPerBatch: 3,
    ingredients: [{ name: 'Mixed salad greens', quantity: 5, unit: 'oz' }],
  },
  {
    id: 'base-roasted-potatoes',
    name: 'Roasted Potatoes',
    category: 'base',
    flavorProfiles: ['American', 'Mediterranean'],
    nutrition: { calories: 160, protein: 3, carbs: 28, fat: 5 },
    servingsPerBatch: 5,
    ingredients: [
      { name: 'Yukon gold potatoes', quantity: 2, unit: 'lb' },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp' },
    ],
  },

  // ----- Proteins ----------------------------------------------------------
  {
    id: 'protein-grilled-chicken',
    name: 'Grilled Chicken Thighs',
    category: 'protein',
    flavorProfiles: ['Mexican', 'Mediterranean', 'American', 'East Asian'],
    nutrition: { calories: 220, protein: 28, carbs: 0, fat: 11 },
    servingsPerBatch: 6,
    ingredients: [{ name: 'Boneless chicken thighs', quantity: 2, unit: 'lb' }],
  },
  {
    id: 'protein-chicken-breast',
    name: 'Lemon Chicken Breast',
    category: 'protein',
    flavorProfiles: ['Mediterranean', 'Italian', 'American', 'Neutral'],
    nutrition: { calories: 165, protein: 31, carbs: 1, fat: 4 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Chicken breast', quantity: 2, unit: 'lb' },
      { name: 'Lemon', quantity: 1, unit: 'whole' },
    ],
  },
  {
    id: 'protein-crispy-tofu',
    name: 'Crispy Tofu',
    category: 'protein',
    flavorProfiles: ['East Asian', 'Thai'],
    nutrition: { calories: 180, protein: 16, carbs: 8, fat: 10 },
    servingsPerBatch: 5,
    ingredients: [
      { name: 'Extra-firm tofu', quantity: 2, unit: 'block' },
      { name: 'Cornstarch', quantity: 3, unit: 'tbsp' },
    ],
  },
  {
    id: 'protein-ground-beef',
    name: 'Seasoned Ground Beef (93%)',
    category: 'protein',
    flavorProfiles: ['Mexican', 'American'],
    nutrition: { calories: 215, protein: 23, carbs: 2, fat: 13 },
    servingsPerBatch: 4,
    ingredients: [{ name: '93% lean ground beef', quantity: 1, unit: 'lb' }],
  },
  {
    id: 'protein-chickpeas',
    name: 'Roasted Chickpeas',
    category: 'protein',
    flavorProfiles: ['Mediterranean', 'Middle Eastern', 'Indian'],
    nutrition: { calories: 150, protein: 8, carbs: 22, fat: 4 },
    servingsPerBatch: 5,
    ingredients: [{ name: 'Chickpeas', quantity: 2, unit: 'can' }],
  },
  {
    id: 'protein-shrimp',
    name: 'Garlic Shrimp',
    category: 'protein',
    flavorProfiles: ['East Asian', 'Thai', 'Mediterranean'],
    nutrition: { calories: 120, protein: 23, carbs: 1, fat: 2 },
    servingsPerBatch: 4,
    ingredients: [
      { name: 'Shrimp, peeled', quantity: 1, unit: 'lb' },
      { name: 'Garlic', quantity: 4, unit: 'clove' },
    ],
  },

  // ----- Vegetables --------------------------------------------------------
  {
    id: 'veg-roasted-broccoli',
    name: 'Roasted Broccoli',
    category: 'vegetable',
    flavorProfiles: ['East Asian', 'Mediterranean', 'American', 'Neutral'],
    nutrition: { calories: 55, protein: 4, carbs: 8, fat: 2 },
    servingsPerBatch: 5,
    ingredients: [{ name: 'Broccoli', quantity: 2, unit: 'head' }],
  },
  {
    id: 'veg-slaw',
    name: 'Cabbage Slaw',
    category: 'vegetable',
    flavorProfiles: ['Mexican', 'Thai', 'East Asian'],
    nutrition: { calories: 35, protein: 2, carbs: 7, fat: 0 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Green cabbage', quantity: 1, unit: 'head' },
      { name: 'Carrot', quantity: 2, unit: 'whole' },
    ],
  },
  {
    id: 'veg-cucumber-tomato',
    name: 'Cucumber-Tomato Salad',
    category: 'vegetable',
    flavorProfiles: ['Mediterranean', 'Middle Eastern'],
    nutrition: { calories: 40, protein: 2, carbs: 8, fat: 0 },
    servingsPerBatch: 4,
    ingredients: [
      { name: 'Cucumber', quantity: 2, unit: 'whole' },
      { name: 'Roma tomato', quantity: 3, unit: 'whole' },
    ],
  },
  {
    id: 'veg-peppers-onions',
    name: 'Sautéed Peppers & Onions',
    category: 'vegetable',
    flavorProfiles: ['Mexican', 'Italian', 'American'],
    nutrition: { calories: 60, protein: 1, carbs: 9, fat: 3 },
    servingsPerBatch: 4,
    ingredients: [
      { name: 'Bell pepper', quantity: 2, unit: 'whole' },
      { name: 'Yellow onion', quantity: 1, unit: 'whole' },
    ],
  },
  {
    id: 'veg-roasted-sweet-potato',
    name: 'Roasted Sweet Potato',
    category: 'vegetable',
    flavorProfiles: ['American', 'Mediterranean', 'Indian'],
    nutrition: { calories: 115, protein: 2, carbs: 27, fat: 0 },
    servingsPerBatch: 5,
    ingredients: [{ name: 'Sweet potato', quantity: 2, unit: 'lb' }],
  },

  // ----- Sauces (flavor drivers) ------------------------------------------
  {
    id: 'sauce-chipotle-crema',
    name: 'Chipotle Crema',
    category: 'sauce',
    flavorProfiles: ['Mexican'],
    nutrition: { calories: 70, protein: 1, carbs: 3, fat: 6 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Greek yogurt', quantity: 1, unit: 'cup' },
      { name: 'Chipotle in adobo', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'sauce-peanut',
    name: 'Peanut Sauce',
    category: 'sauce',
    flavorProfiles: ['Thai', 'East Asian'],
    nutrition: { calories: 110, protein: 4, carbs: 6, fat: 8 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Peanut butter', quantity: 0.5, unit: 'cup' },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'Lime', quantity: 1, unit: 'whole' },
    ],
  },
  {
    id: 'sauce-lemon-tahini',
    name: 'Lemon-Tahini',
    category: 'sauce',
    flavorProfiles: ['Mediterranean', 'Middle Eastern'],
    nutrition: { calories: 90, protein: 3, carbs: 4, fat: 7 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Tahini', quantity: 0.33, unit: 'cup' },
      { name: 'Lemon', quantity: 1, unit: 'whole' },
      { name: 'Garlic', quantity: 1, unit: 'clove' },
    ],
  },
  {
    id: 'sauce-soy-ginger',
    name: 'Soy-Ginger Glaze',
    category: 'sauce',
    flavorProfiles: ['East Asian'],
    nutrition: { calories: 45, protein: 1, carbs: 9, fat: 0 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Soy sauce', quantity: 0.25, unit: 'cup' },
      { name: 'Fresh ginger', quantity: 1, unit: 'thumb' },
      { name: 'Honey', quantity: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'sauce-tzatziki',
    name: 'Tzatziki',
    category: 'sauce',
    flavorProfiles: ['Mediterranean', 'Middle Eastern'],
    nutrition: { calories: 40, protein: 3, carbs: 3, fat: 2 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Greek yogurt', quantity: 1, unit: 'cup' },
      { name: 'Cucumber', quantity: 1, unit: 'whole' },
      { name: 'Dill', quantity: 1, unit: 'bunch' },
    ],
  },
  {
    id: 'sauce-salsa-verde',
    name: 'Salsa Verde',
    category: 'sauce',
    flavorProfiles: ['Mexican'],
    nutrition: { calories: 25, protein: 1, carbs: 5, fat: 0 },
    servingsPerBatch: 8,
    ingredients: [
      { name: 'Tomatillo', quantity: 6, unit: 'whole' },
      { name: 'Jalapeño', quantity: 1, unit: 'whole' },
    ],
  },

  // ----- Garnishes ---------------------------------------------------------
  {
    id: 'garnish-cilantro-lime',
    name: 'Cilantro + Lime',
    category: 'garnish',
    flavorProfiles: ['Mexican', 'Thai'],
    nutrition: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    servingsPerBatch: 6,
    ingredients: [
      { name: 'Cilantro', quantity: 1, unit: 'bunch' },
      { name: 'Lime', quantity: 1, unit: 'whole' },
    ],
  },
  {
    id: 'garnish-feta',
    name: 'Crumbled Feta',
    category: 'garnish',
    flavorProfiles: ['Mediterranean', 'Middle Eastern'],
    nutrition: { calories: 75, protein: 4, carbs: 1, fat: 6 },
    servingsPerBatch: 6,
    ingredients: [{ name: 'Feta', quantity: 4, unit: 'oz' }],
  },
  {
    id: 'garnish-sesame',
    name: 'Toasted Sesame Seeds',
    category: 'garnish',
    flavorProfiles: ['East Asian', 'Thai'],
    nutrition: { calories: 35, protein: 1, carbs: 1, fat: 3 },
    servingsPerBatch: 10,
    ingredients: [{ name: 'Sesame seeds', quantity: 2, unit: 'tbsp' }],
  },
  {
    id: 'garnish-avocado',
    name: 'Sliced Avocado',
    category: 'garnish',
    flavorProfiles: ['Mexican', 'American'],
    nutrition: { calories: 80, protein: 1, carbs: 4, fat: 7 },
    servingsPerBatch: 2,
    ingredients: [{ name: 'Avocado', quantity: 1, unit: 'whole' }],
  },
  {
    id: 'garnish-peanuts',
    name: 'Toasted Peanuts',
    category: 'garnish',
    flavorProfiles: ['Thai', 'East Asian'],
    nutrition: { calories: 85, protein: 4, carbs: 3, fat: 7 },
    servingsPerBatch: 6,
    ingredients: [{ name: 'Roasted peanuts', quantity: 0.5, unit: 'cup' }],
  },
  {
    id: 'garnish-herbs',
    name: 'Fresh Herbs (parsley/mint)',
    category: 'garnish',
    flavorProfiles: ['Mediterranean', 'Middle Eastern', 'Italian'],
    nutrition: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    servingsPerBatch: 8,
    ingredients: [{ name: 'Fresh parsley', quantity: 1, unit: 'bunch' }],
  },
]

export const SEED_MEALS: Meal[] = [
  {
    id: 'meal-chipotle-chicken-bowl',
    name: 'Chipotle Chicken Bowl',
    formFactor: 'bowl',
    flavorProfile: 'Mexican',
    componentIds: [
      'base-cilantro-lime-rice',
      'protein-grilled-chicken',
      'veg-slaw',
      'sauce-chipotle-crema',
      'garnish-cilantro-lime',
    ],
    notes: 'High-protein, batch-prep favorite. Add hot sauce to taste.',
  },
  {
    id: 'meal-thai-peanut-tofu',
    name: 'Thai Peanut Tofu Bowl',
    formFactor: 'bowl',
    flavorProfile: 'Thai',
    componentIds: [
      'base-jasmine-rice',
      'protein-crispy-tofu',
      'veg-roasted-broccoli',
      'sauce-peanut',
      'garnish-peanuts',
    ],
  },
  {
    id: 'meal-med-chickpea-bowl',
    name: 'Mediterranean Chickpea Bowl',
    formFactor: 'bowl',
    flavorProfile: 'Mediterranean',
    componentIds: [
      'base-farro',
      'protein-chickpeas',
      'veg-cucumber-tomato',
      'sauce-lemon-tahini',
      'garnish-feta',
    ],
  },
]

export const DEFAULT_TARGETS: Targets = { calories: 1800, protein: 150 }
export const DEFAULT_PERIOD_DAYS = 5
